<a href="https://colab.research.google.com/github/apriliaeva/Tugas-Algoritma/blob/main/2208541037%20Aprilia%20Eva%20Tugas%20V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list.
Penggambarannya seperti sebuah matrik.

In [1]:
#Latihan 1

#inisialisasi variabel dengan list 2 dimensi
matriks = [
    [1,2,3,4],
    [7,8,9,10],
    [5,6,11,12],
]
#variabel matriks diatas akan dikenali sebagai matriks dimana memiliki baris dan kolom
print('Matriks : \n', matriks)

print('\nMatriks baris pertama: \n', matriks[0])
#baris diatas akan memanggil baris pertama dari matriks (dimana baris dimulai dari urutan 0)

print('\nMatriks baris kedua kolom keempat: \n', matriks[1][3])
#baris diatas akan memanggil baris ke 2 kolom ke 4 dari matriks (dimana baris & kolom dimulai dari urutan 0)

#kita dapat mengubah/mengganti nilai pada matriks
#ganti nilai matriks baris pertama kolom pertama menjadi sama dengan 20  
matriks[0][0] = 20
print('\nUbah nilai matriks baris pertama kolom pertama menjadi: \n', matriks[0][0]) 
#perintah print akan mencetak dan mengganti baris pertama kolom pertama dengan angka 20

print('\nMatriks terbaru: \n', matriks)
#perintah print akan mencetak dan menampilkan matriks terbaru

Matriks : 
 [[1, 2, 3, 4], [7, 8, 9, 10], [5, 6, 11, 12]]

Matriks baris pertama: 
 [1, 2, 3, 4]

Matriks baris kedua kolom keempat: 
 10

Ubah nilai matriks baris pertama kolom pertama menjadi: 
 20

Matriks terbaru: 
 [[20, 2, 3, 4], [7, 8, 9, 10], [5, 6, 11, 12]]


In [2]:
#Latihan 2 [menggunakan perulangan for]
#kita akan menggunakan for untuk mengurutkan isi variabel list dua dimensi

#inisialisasi variabel dengan list 2 dimensi 
trejo = [
    ['Uncuk', 'Jiun', 'Oci', 'Ajun'],
    ['Cio', 'Jeyok', 'Asahoy', 'Adam'],
    ['Dobby', 'Ruto', 'Uwo', 'Wawan']
]
print('Trejo Member First: \n', trejo)

#cetak teks & urutkan baris pertama pada variabel list 2 dimensi diatas
print('\nHyung Line in Trejo :')
for hyung_line in trejo[0]:
#for akan mengurutkan data pada baris pertama
  print(hyung_line)
#baris diatas akan memanggil baris pertama pada variabel trejo

#cetak teks & urutkan baris kedua pada variabel list 2 dimensi diatas
print('\nMiddle Line in Trejo :')
for middle_line in trejo[1]:
#for akan mengurutkan data pada baris kedua
  print(middle_line)
#baris diatas akan memanggil baris kedua pada variabel trejo

#cetak teks & urutkan baris ketiga pada variabel list 2 dimensi diatas
print('\nMaknae Line in Trejo :')
for maknae_line in trejo[2]:
#for akan mengurutkan data pada baris kedua
  print(maknae_line)
#baris diatas akan memanggil baris ketiga pada variabel trejo

#kita dapat menampilkan semua isi variabel list 2 dimensi diatas dengan menggunakan perulangan bersarang
print('\nAll Trejo members:')
for all in trejo:
#for akan mengurutkan data pada variabel trejo 
#namun jika langsung di print disini [print(all)] outputnya akan berupa matriks 
  for treasure in all:
#for akan mengurutkan data pada variabel all 
    print(treasure)
#baris diatas akan memanggil data pada variabel treasure

Trejo Member First: 
 [['Uncuk', 'Jiun', 'Oci', 'Ajun'], ['Cio', 'Jeyok', 'Asahoy', 'Adam'], ['Dobby', 'Ruto', 'Uwo', 'Wawan']]

Hyung Line in Trejo :
Uncuk
Jiun
Oci
Ajun

Middle Line in Trejo :
Cio
Jeyok
Asahoy
Adam

Maknae Line in Trejo :
Dobby
Ruto
Uwo
Wawan

All Trejo members:
Uncuk
Jiun
Oci
Ajun
Cio
Jeyok
Asahoy
Adam
Dobby
Ruto
Uwo
Wawan


#5.17 Tuples

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya.

In [3]:
#Latihan 1

#inisialisasi variabel kata
kata = ('saya','sa','gua','kau','ko','loe','saya')

#akan ditampilkan sinonim dari kata aku dgn menggunakan batas indeks
print('Sinonim dari kata aku adalah ', kata[0:3])
#perintah print diatas akan mencetak & menampilkan indeks pertama sampai ke 3 
#kodenya jg dapat berupa print(''kata[:3]) 

#akan ditampilkan antonim dari kata aku dgn menggunakan batas indeks
print('\nAntonim dari kata aku adalah ', kata[3:6])
#perintah print diatas akan mwncwtak & menampilkan indeks ke 3 sampai ke 5 

#akan diurutkan kebawah sinonim dari kata aku menggunakan perulangan for
print('\nSinonim dari kata aku:')
for aku in kata[0:3]:
  print(aku)

#akan ditampilkan banyaknya suatu kata dalam variabel kata dgn menggunakan 'variabel.count()'
print('\nBanyaknya kata aku dalam variabel kata adalah ', kata.count('aku'))
#output nol karena tdk terdapat kata aku dalam variabel kata

print('\nBanyaknya kata saya dalam variabel kata adalah ', kata.count('saya'))

#akan ditampilkan urutan kata dalam variabel kata dengan menggunakan 'variabel.index()'
print('\nUrutan kata ko pada variabel kata adalah ', kata.index('ko'))

print('\nUrutan kata sa pada variabel kata adalah ', kata.index('sa'))

Sinonim dari kata aku adalah  ('saya', 'sa', 'gua')

Antonim dari kata aku adalah  ('kau', 'ko', 'loe')

Sinonim dari kata aku:
saya
sa
gua

Banyaknya kata aku dalam variabel kata adalah  0

Banyaknya kata saya dalam variabel kata adalah  2

Urutan kata ko pada variabel kata adalah  4

Urutan kata sa pada variabel kata adalah  1


In [4]:
#Latihan 2 [update nilai & hapus nilai dalam tuple]
#seperti penjelasannya tuple tdk dpt dirubah isinya, yang berarti Anda tidak dapat menambah atau mengubah nilai elemen tuple
#shg fungsi append() dan remove() tdk dpt digunakan 

#untuk membuat tuple baru, dapat dilakukan dgn mengambil bagian dari tuple yang ada untuk membuat tuple baru 
#inisialisasi variabel
umur1 = (17,18,19,19)
umur2 = (16,20,24)
print('Umur kelompok pertama, sbb: \n', umur1)
print('\nUmur kelompok kedua, sbb: \n', umur2)
usia = umur1 + umur2
#variabel usia akan berisi gabungan elemen dari variabel umur1 & umur2
print('\nUmur kelompok baru adalah ', usia)
#perintah diatas akan mencetak teks menampilkan variabel usia 

#menghapus nilai elemen tuple individual tidak mungkin dapat dilakukan, shg menghapus tuple hanya dapat dilakukan dgn menghapus keseluruhan tuple 
#hapus tuple dgn statement del

#gunakan variabel sebelumnya
#hapus tuple umur1 dgn statement del
del umur1
#lalu kita buat kembali tuple yg baru pada variabel umur1 
umur1 = (14,15,18)
print('\nUmur kelompok pertama yang baru, sbb: \n', umur1)

#kembali membuat tuple yg baru
usia_baru = umur1 + umur2
print('\nSehingga, umur kelompok setelah diperbaharui adalah ', usia_baru)

Umur kelompok pertama, sbb: 
 (17, 18, 19, 19)

Umur kelompok kedua, sbb: 
 (16, 20, 24)

Umur kelompok baru adalah  (17, 18, 19, 19, 16, 20, 24)

Umur kelompok pertama yang baru, sbb: 
 (14, 15, 18)

Sehingga, umur kelompok setelah diperbaharui adalah  (14, 15, 18, 16, 20, 24)


#5.18 Dictionaries

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [5]:
#Latihan 1

#inisialisasi data dictionary
data_diri = {
    'nama' : 'Aprilia Eva',                                 #nama berisi string ('Aprilia Eva')
    'umur' : 19,                                            #umur berisi integer (22)
    'hoby' : ['nonton', 'rebahan', 'medengarkan musik'],    #hoby berisi list dari string
    'menikah' : False,                                      #menikah berisi boolean (False)  
}

#akan dipanggil data_diri diatas
print('Data diri :',data_diri)

#tanda yg digunakan utk memanggil data pada dictionary adalah ['']
#akan dipanggil nama pada dictionary data_diri
print('nama : ', data_diri['nama'])
#akan dipanggil nama pada dictionary data_diri dgn menggunakan huruf kapital
print('nama : ', data_diri['Nama'])
#error karena N pada nama berupa huruf kapital sdgkan pada data_diri n berupa huruf kecil

Data diri : {'nama': 'Aprilia Eva', 'umur': 19, 'hoby': ['nonton', 'rebahan', 'medengarkan musik'], 'menikah': False}
nama :  Aprilia Eva


KeyError: ignored

In [6]:
#Lanjutan

#tanda yg digunakan utk memanggil data pada dictionary dgn fungsi get adalah ('')
#akan dipanggil nama pada dictionary data_diri dgn menggunakan fungsi get
print('nama : ', data_diri.get('nama'))
#akan dipanggil nama pada dictionary data_diri dgn menggunakan huruf kapital dgn menggunakan fungsi get
print('nama : ', data_diri.get('Nama'))
#disini outputnya tdk error walaupun huruf yg digunakan berbeda begitu pun jika di cari sesuatu yg tdk terdapat dalam dictionary
#shg, jika tidak ada outputnya akan berupa "None"

#akan ditambahkan data pada dictionary
data_diri['zodiak'] = 'Taurus'
#ditambahkan data berupa zodiak dalam dictionary

#akan dipanggil data_diri diatas menggunakan fungsi get
print('\nData diri saya sebagai berikut:')
print('Nama :', data_diri.get('nama'))
print('Umur :', data_diri.get('umur'))
print('Hoby :', data_diri.get('hoby'))
print('Menikah :', data_diri.get('menikah'))
print('Zodiak : ', data_diri.get('zodiak'))

nama :  Aprilia Eva
nama :  None

Data diri saya sebagai berikut:
Nama : Aprilia Eva
Umur : 19
Hoby : ['nonton', 'rebahan', 'medengarkan musik']
Menikah : False
Zodiak :  Taurus


In [7]:
#Latihan 2 [menggunakan input & for]

#inisialisasi data dictionary
angka = {
    '0' : 'nol',
    '1' : 'satu',
    '2' : 'dua',
    '3' : 'tiga',
    '4' : 'empat',
    '5' : 'lima',
    '6' : 'enam',
    '7' : 'tujuh',
    '8' : 'delapan',
    '9' : 'sembilan'
}

#gunakan input utk memasukkan no 
no_HP = input('Masukkan nomor HP :')
no_angka = ''
for isi in no_HP:
#for akan mengurutkan hasil input dari nomor HP
  no_angka += angka.get(isi) + ' '
print(no_angka)
#lalu akan dipanggil data dari hasil input shg hasil outputnya berupa string

Masukkan nomor HP :081236789010
nol delapan satu dua tiga enam tujuh delapan sembilan nol satu nol 


#5.19 Fungsi dalam Phyton

Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi dibentuk untuk menghidari pengulangan pembuatan program secara manual dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat, setiap fungsi tersebut dibutuhkan tinggal kita panggil.

In [8]:
#Latihan [menggunakan fungsi def]
#rumus umum sintaks adalah sebagai berikut : def <nama_fungsi>(parameters)

#input variabel dari firs_name & last name
first_name = input('your first name is ')
last_name = input('your last name is ')

#kode dibawah ini akan memanggil variabel diatas menjadi sebuah variabel dengan nama full_name
def full_name(first_name, last_name):
  print(f'your full name is {first_name} {last_name}')
full_name(first_name,last_name)
#baris diatas akan menampilkan output dari kode sebelumnya

your first name is Lalisa
your last name is Manoban
your full name is Lalisa Manoban


###5.19.1 Tugas Fungsi pada Python

Ada dua jenis tugas fungsi pada Python yaitu:
- Menjalankan perintah.
- Menampilkan hasil perhitungan.

In [9]:
#Latihan [menampilkan hasil perhitungan menggunakan return]

#baris ini mendefinisikan luas persegi dgn sisi
def luas_persegi (sisi):
  return sisi * sisi
#return akan mengembalikan nilai dari fungsi yang jika kita panggil

#baris ini tidak menghasilkan output apa pun karena tdk berada print
luas_persegi(10)

#baris ini akan menghasilkan output dgn sisinya=4, yg berarti 4*4
print('Luas persegi dengan sisi 4 adalah:', luas_persegi(4))

#kita juga bisa simpan di dalam variabel, seperti berikut
persegi_besar = luas_persegi(100)
persegi_kecil = luas_persegi(50)

#baris ini akan menghasilkan output berupa total luas dari 2 variabel diatas
print('Toal luas persegi besar dan kecil adalah:', persegi_besar + persegi_kecil)

Luas persegi dengan sisi 4 adalah: 16
Toal luas persegi besar dan kecil adalah: 12500


In [10]:
#Latihan [menggunakan lebih dari 1 return]

#Jika return dieksekusi, maka semua proses yang ada di dalam blok kode fungsi tersebut akan berhenti
#Sehingga, misalkan kita memiliki lebih dari 1 buah return, maka hanya ada satu return saja yang dieksekusi. Dan ketika sebuah return telah dieksekusi, semua perintah yang ada di bawahnya akan di-skip

#baris ini mendefinisikan presentase dgn (total,jumlah)
def persentase (total, jumlah):
  if (total >= 0 and total <= jumlah):
#baris diatas berarti jika total >=0 & total <= jumlah, maka berlaku syntax pada baris dibawah  
    return total / jumlah * 100

#kode ini akan berlaku jika total >=0 & total <= jumlah tdk terpenuhi
  return False

#baris ini akan menampilkan output sesuai total & jumlahnya (dimana total & jumlah memenuhi persyaratan) 
print('Presentase dari total = 30 & jumlah = 90 adalah ',persentase(30,90))

#outputnya False karena syarat total <= jumlah tdk terpenuhi
print('Presentase dari total = 90 & jumlah = 50 adalah ',persentase(90,50))


Presentase dari total = 30 & jumlah = 90 adalah  33.33333333333333
Presentase dari total = 90 & jumlah = 50 adalah  False


#5.20 Numpy

Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.


In [11]:
#Sebelum menggunakan Numpy di Python, terlebih dahulu library ini harus diimport

import numpy as np

###5.20.1 Perintah Dasar pada Numpy

In [12]:
#Latihan 

#membuat array
a = np.array([10,11,12,13,14])
print('Array (1): ')
print(a)
#printah print diatas akan memanggil variabel list a

#membuat array 2 dimensi
b = np.array([[1,2,3],[4,5,6]])
print('\nArray 2 dimensi (2): ')
print(b)
#printah print diatas akan memanggil variabel list b

#membuat array 3 dimensi
c = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[1,0,1]],
              [[2,3,4],[5,7,8]]])  
print('\nArray 3 dimensi (3): ')
print(c)

#akan ditentukan dimensi arrray & jumlah array
#fungsi .ndim berfungsi menghitung dimensi array 
#fungsi .shape berfungsi menghitung isi dari array

print('\nDimensi array (1): \n', a.ndim)
print('Dimensi array (2): \n', b.ndim)
print('Dimensi array (3): \n', c.ndim)
print('Jumlah array (1): \n', a.shape)
print('Jumlah array (2): \n', b.shape)
print('Jumlah array (3): \n', c.shape)

Array (1): 
[10 11 12 13 14]

Array 2 dimensi (2): 
[[1 2 3]
 [4 5 6]]

Array 3 dimensi (3): 
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 0 1]]

 [[2 3 4]
  [5 7 8]]]

Dimensi array (1): 
 1
Dimensi array (2): 
 2
Dimensi array (3): 
 3
Jumlah array (1): 
 (5,)
Jumlah array (2): 
 (2, 3)
Jumlah array (3): 
 (3, 2, 3)


###5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [13]:
#Latihan 1

#membuat array
d = np.array([[0,1,2,3],[1,2,1,2],[2,3,2,3],[3,4,3,4]])
print('Diketahui array : \n', d)

#memanggil baris kedua   
print('\nBaris kedua :\n', d[1,:])
#memanggil kolom keempat
print('Kolom keempat :\n', d[:,3])
#memanggil baris ketiga kolom pertama
print('Baris ketiga kolom pertama :\n', d[2,0])
#mengganti elemen pada baris pertama kolom pertama
d[0,0] = 10
print('\nArray yang baru : \n',d)
d[0,1:2]

Diketahui array : 
 [[0 1 2 3]
 [1 2 1 2]
 [2 3 2 3]
 [3 4 3 4]]

Baris kedua :
 [1 2 1 2]
Kolom keempat :
 [3 2 3 4]
Baris ketiga kolom pertama :
 2

Array yang baru : 
 [[10  1  2  3]
 [ 1  2  1  2]
 [ 2  3  2  3]
 [ 3  4  3  4]]


array([1])

In [15]:
#Latihan 2

#melakukan slicing di array dgn np.arange
#arange(start, stop, step)
i = np.arange(1, 10, 2) 

#lalu kita panggil dgn kode seperti dibawah
print('Diketahui array: \n',i)
print(i[2:8])
print(i[:5])
print(i[5:])
print(i[::2])
print(i[1::2])
print(i[1:7:2])
print(i[::-1])

Diketahui array: 
 [1 3 5 7 9]
[5 7 9]
[1 3 5 7 9]
[]
[1 5 9]
[3 7]
[3 7]
[9 7 5 3 1]


###5.20.3 Matrix pada Numpy


In [16]:
#Latihan

#ones berfungsi membuat array dengan semua elemen bernilai 1
np.ones((2,5))
#kode diatas membuat array matriks elemen 1 dgn 2 baris & 5 kolom

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#zeros berfungsi membuat array dengan semua elemen bernilai 0
np.zeros((3,7))
#kode diatas akan membuat array matriks elemen 0 dgn 3 baris & 7 kolom

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
#identity adalah jenis matrik identitas
#dimana semua elemen pada diagonal utamanya adalah satu (1) dan semua elemen lainnya adalah nol (0)
np.identity(4)
#kode diatas akan membuat array matriks identitas dgn baris & kolom = 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#full digunakan untuk mengisi array yang sudah ada dengan nilai yang sama
np.full((3,3),7)
#kode diatas akan membuat array matriks dgn elemen 7 & dgn 3 baris & 3 kolom

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
#fungsi random digunakan untuk menghasilkan angka acak di Python
#tidak benar-benar acak, melainkan ini digunakan untuk menghasilkan angka pseudo-acak
np.random.rand(4,4)

array([[0.69521848, 0.26239756, 0.42666766, 0.10020772],
       [0.7441285 , 0.92884129, 0.12278222, 0.98592825],
       [0.00362779, 0.91321903, 0.67099041, 0.4528955 ],
       [0.55106637, 0.51404861, 0.72923513, 0.78362788]])

In [21]:
#random.randint akan menghasilkan sebuah angka dengan tipe data integer acak dari parameter yang diberikan
#Fungsi ini membutuhkan 2 parameter yaitu angka minimum dan angka maksimum, dan python akan memberikan sebuah angka diantara 2 angka tersebut
np.random.randint(0,10,size=(2,4))

array([[7, 7, 5, 8],
       [1, 9, 7, 6]])

###5.20.4 Copy pada Numpy

In [22]:
#Latihan

#membuat array
a = np.array([6,7,8,9])
print('Diketahui array (a) : \n',a)
#menampilkan array

#membuat nilai a = b
b = a
print('Diketahui array (b) : \n',b)

#akan diubah data indeks ke 0 (data pertama) menjadi 11
b[0] = 11
print('Diketahui array (b) baru : \n',b)

#sehingga nilai array a jg akan berubah
print('Sehingga array (a) : \n',a)

#lalu buat array baru dgn elemen yg sama seperti di awal
c = np.array([6,7,8,9])
print('Diketahui array (c) : \n',c)

#gunakan copy
d = c.copy()
print('Diketahui array (d) : \n',d)

#ubah data indeks ke 0 (data pertama) menjadi 11
d[0] = 11
print('Sehingga array (d) : \n',d)

#dapat dilihat outputnya tidak mempengaruhi array yg asli
print('Array (c) : \n',c)

Diketahui array (a) : 
 [6 7 8 9]
Diketahui array (b) : 
 [6 7 8 9]
Diketahui array (b) baru : 
 [11  7  8  9]
Sehingga array (a) : 
 [11  7  8  9]
Diketahui array (c) : 
 [6 7 8 9]
Diketahui array (d) : 
 [6 7 8 9]
Sehingga array (d) : 
 [11  7  8  9]
Array (c) : 
 [6 7 8 9]


###5.20.5 Operasi Matematika pada Numpy

In [23]:
#Latihan

#membuat array
x = np.array([10,12,14,16,18])
y = np.array([2,2,2,2,2])
print('Diketahui x = [10,12,14,16,18] & y = [2,2,2,2,2]\n')

#akan dipanggil sesuai operasi yg digunakan
print('penjumlahan (x + y) = ',  x + y) 
print('pengurangan (x - y) = ', x - y)
print('perkalian (x * y) = ', x * y)
print('pembagian (x / y) = ', x / y)
print('perpangkatan (x ** y) = ', x ** y)

Diketahui x = [10,12,14,16,18] & y = [2,2,2,2,2]

penjumlahan (x + y) =  [12 14 16 18 20]
pengurangan (x - y) =  [ 8 10 12 14 16]
perkalian (x * y) =  [20 24 28 32 36]
pembagian (x / y) =  [5. 6. 7. 8. 9.]
perpangkatan (x ** y) =  [100 144 196 256 324]


###5.20.6 Perkalian Matrik pada Numpy

In [24]:
#Latihan 

#membuat array
matrik1 = np.array([[2,1],
                     [1,2]])
matrik2 = np.array([[2,2],
                     [1,1]])   

#kita kalikan matrik1 dengan matrik2 dgn beberapa cara, seperti berikut
perkalian_biasa = matrik1*matrik2
perkalian_matrik_cara1 = np.dot(matrik1,matrik2)
perkalian_matrik_cara2 = matrik1.dot(matrik2)

#akan dipanggil hasil perkalian dari matrik sesuai dgn cara yg digunakan
print("Diketahui Matrik 1 :")
print(matrik1)

print("Diketahui Matrik 2 :")
print(matrik2)

print("Perkalian Biasa Matrik : ")
print(perkalian_biasa)

print("Perkalian Matrik Cara 1 : ")
print(perkalian_matrik_cara1)

print("Perkalian Matrik Cara 2 : ")
print(perkalian_matrik_cara2)

Diketahui Matrik 1 :
[[2 1]
 [1 2]]
Diketahui Matrik 2 :
[[2 2]
 [1 1]]
Perkalian Biasa Matrik : 
[[4 2]
 [1 2]]
Perkalian Matrik Cara 1 : 
[[5 5]
 [4 4]]
Perkalian Matrik Cara 2 : 
[[5 5]
 [4 4]]


###5.20.7 min, max dan sum pada Numpy

In [25]:
#Latihan

#membuat array
a = np.array([[0,1,2,],
              [4,5,6], 
              [7,8,9]])
#memanggil & menampilkan matrik a
print('Diketahui matrik (a) : \n',a)

#b merupakan nilai minimal atau paling kecil di matriks a
b = np.min(a) 
print('\nNilai minimal dari matrik a : \n',b)

#b merupakan nilai minimal pada sumbu-0 (mengarah kebawah/secara vertikal)
c = np.min(a,axis=0) 
print('\nNilai minimal pada sumbu-0 : \n',c)

#d merupakan nilai minimal pada sumbu-1 (mengarah kesamping/secara horizontal)
d = np.min(a,axis=1) 
print('\nNilai minimal pada sumbu-1 : \n',d)

#e merupakan nilai maksimal atau paling besar di matriks a
e = np.max(a) 
print('\nNilai maksimal dari matrik a : \n',e)

#f merupakan nilai maksimal pada sumbu-0 (mengarah kebawah/secara vertikal)
f = np.max(a,axis=0) 
print('\nNilai maksimal pada sumbu-0 : \n',f)

#g merupakan nilai maksimal pada sumbu-1 (mengarah kesamping/secara horizontal)
g= np.max(a,axis=1) 
print('\nNilai maksimal pada sumbu-1 : \n',g)

#h merupakan hasil penjumlahan dari semua elemen di matriks a
h = np.sum(a) 
print('\nHasil penjumlahan semua elemen di matrik a : \n',h)

#i merupakan hasil penjumlahan sumbu-0 (mengarah kebawah/secara vertikal)
i = np.sum(a,axis=0) 
print('\nHasil penjumlahan semua elemen di matrik a pada sumbu-0 : \n',i)

#j merupakan hasil penjumlahan sumbu-1 (mengarah kesamping/secara horizontal)
j= np.sum(a, axis=1)
print('\nHasil penjumlahan semua elemen di matrik a pada sumbu-1 : \n',j)

Diketahui matrik (a) : 
 [[0 1 2]
 [4 5 6]
 [7 8 9]]

Nilai minimal dari matrik a : 
 0

Nilai minimal pada sumbu-0 : 
 [0 1 2]

Nilai minimal pada sumbu-1 : 
 [0 4 7]

Nilai maksimal dari matrik a : 
 9

Nilai maksimal pada sumbu-0 : 
 [7 8 9]

Nilai maksimal pada sumbu-1 : 
 [2 6 9]

Hasil penjumlahan semua elemen di matrik a : 
 42

Hasil penjumlahan semua elemen di matrik a pada sumbu-0 : 
 [11 14 17]

Hasil penjumlahan semua elemen di matrik a pada sumbu-1 : 
 [ 3 15 24]
